base:
# 求職登録有無欄
# 求職登録している場合はkyushokuUmuの値は1。登録していなければ0。
# 求職登録をしている場合、kyushokuNumber1とkyushokuNumber2にそれぞれ入力。
# kyushokuNumber1は半角数字5桁、kyushokuNumber2は半角数字8桁で入力。
  kyushokuUmu: 0
  kyushokuNumber1: 
  kyushokuNumber2: 
# 求人情報の種類欄
# 一般(フルタイム)の場合は1、一般(パート)の場合は2、学生の場合は3を入力
  kyujinShurui: 1

# 派遣・請負欄
# 派遣・請負を除くのであれば1。除かないのであれば0。
  hakenOrUkeoi: 
# 賃金欄
# ``求人情報の種類"で一般(フルタイム)の場合は月給欄への入力と``手当等を含む"のチェックするかどうか。
# チェックする場合は1、しない場合は0。
# 一般(パート)の場合は時給欄への入力。
# 学生の場合は上記のどちらかへの入力。
  gekkyuKagen: 
  teate: 
  jikyuKagen: 
# 希望する職種欄
# 希望する職種を選択。分類はhttps://www.hellowork.go.jp/info/job_dictionary.htmlを参照。
# "A"は専門的・技術的職業、"B"は管理的職業、"C"は事務的職業、"D"は販売の職業、"E"はサービスの職業、"F"は保安の職業、"G"は農林漁業の職業、"H"は運輸・通信の職業、"I"は生産工程・労務の職業
# 選択はアルファベットにて指定。
  kiboShokushu: A

# 都道府県／市区町村名欄
# 各都道府県を番号にて指定。5箇所まで指定可能。各都道府県と番号の対応は以下の通り。
# 01:北海道 02:青森 03:岩手 04:宮城 05:秋田 06:山形 07:福島 08:茨城 09:栃木 10:群馬 11:埼玉 12:千葉 13:東京 14:神奈川 15:新潟
# 16:富山 17:石川 18:福井 19:山梨 20:長野 21:岐阜 22:静岡 23:愛知 24:三重 25:滋賀 26:京都 27:大阪 28:兵庫 29:奈良 30:和歌山
# 31:鳥取 32:島根 33:岡山 34:広島 35:山口 36:徳島 37:香川 38:愛媛 39:高知 40:福岡 41:佐賀 42:長崎 43:熊本 44:大分 45:宮崎
# 46:鹿児島 47:沖縄 59:海外
# *_chikuの部分には市区町村名を入力。空白で区切ることで複数地区を指定可能。
  todofuken1: 
  todofuken1_chiku: 
  todofuken2: 
  todofuken2_chiku: 
  todofuken3: 
  todofuken3_chiku: 
  todofuken4: 
  todofuken4_chiku: 
  todofuken5: 
  todofuken5_chiku: 

# 年齢欄
# その名の通り。半角で指定。
  nenrei: 

# 新着求人欄
# 前営業日に登録された新しい求人のみを検索する場合は1、しない場合は0。
  shinchakuKyujin: 

# 希望する産業欄
# 選択しておくと、詳細条件検索画面でさらに細かい分類から産業を選択することが可能。
# アルファベットにて指定。対応表は以下の通り。
# A:農業，林業 B:漁業 C:鉱業，採石業，砂利採取業 D:建設業 E:製造業 F:電気・ガス・熱供給・水道業 G:情報通信業
# H:運輸業，郵便業 I:卸売業・小売業 J:金融業・保険業 K:不動産業，物品賃貸業 L:学術研究，専門・技術サービス業
# M:宿泊業，飲食サービス業 N:生活関連サービス業，娯楽業 O:教育，学習支援業 P:医療，福祉 Q:複合サービス事業 
# R:サービス業（他に分類されないも S:公務（他に分類されるものを除く T:分類不能の産業
  kiboSangyo: 

# 最終学歴欄
# ``求人情報の種類"で学生を選択した時のみ有効
# 指定は数字にて行う。対応は以下の通り。
# 1:大学院 2:大学 3:短大 4:高等専門学校 5:専修学校 6:公共職業能力開発施設
  saishuGakureki:

# 既卒者の応募欄
# ``求人情報の種類"で学生を選択した時のみ有効
# 既卒の場合は1、そうではない場合は0。
  zennendoSotsugyo: 

# 詳細検索
# 詳細検索を行う場合は値を1にした上で、下のdetailの項目の必要なところを入力。
# 行わない場合は0を入力
  syousai: 1

detail:
# 雇用形態欄
# 雇用形態を指定。``求人情報の種類"で一般(フルタイム)を選択した場合は以下の選択肢から選択可能
# 1:正社員 2:正社員以外 3:登録型派遣 4:常用型派遣
# 雇用形態を指定。``求人情報の種類"で一般(パート)を選択した場合は以下の選択肢から選択可能
# 5:パート労働者 6:登録型派遣パート 7:常用型派遣パート
# 選択は数字にて指定。
  koyoKeitai1: 
  koyoKeitai2: 
  koyoKeitai3: 
  koyoKeitai4: 

# 契約更新の可能性欄
# 契約更新の可能性が有りにチェックをしたい人は1、違う場合は0。
  keiyakuKoshin: 
  
# マイカー通勤欄
# 希望する場合は1、しない場合は0。
  myCarTsukin: 

# フリーワード欄
# キーワードのAND検索をしたい場合は0、OR検索をしたい場合は1。
# フリーワードは空白で区切ることで複数キーワードを指定可能
# 類義語を選択したい場合は1、したくない場合は0。
  freeWordType:
  freeWord:
  freeWordRuigigo:

# 加入保険欄
# 会社が保険(「雇用」「労災」「健康」「厚生」)に加入していることを重視する場合は1、そうじゃない場合は0。
  kanyuHoken:

# 住込欄
# 有りの場合は1、そうじゃない場合は0。
  sumikomi: 

# 入居可能住宅欄
# 単身用ありを希望する場合はtanshinに1を、世帯用ありを希望する場合はsetaiを1に。必要ない場合は0を。
  tanshin:
  setai:

# 利用可能な託児所欄
# 重視する場合は1、そうじゃない場合は0。
  takujijo: 

# 賞与欄
# 重視する場合は1、そうじゃない場合は0。
  shoyo: 

# 希望する産業(詳細)
# baseの希望する産業で選択したものに対応した詳細を選択。以下対応表。
# A:農業，林業 => 01:農業 02:林業
# B:漁業 => 03:漁業(水産養殖業を除く) 04:水産養殖業
# C:鉱業，採石業，砂利採取業 => 05:鉱業，採石業，砂利採取業
# D:建設業 => 06:総合工事業 07:職別工事業(設備工事業を除く) 08:設備工事業
# E:製造業 => 09:食料品製造業 10:飲料・たばこ・飼料製造業 11:繊維工業 12:木材・木製品製造業(家具を除く) 13:家具・装備品製造業 14:パルプ・紙・紙加工品製造業 15:印刷・同関連業 16:化学工業 17:石油製品・石炭製品製造業 
#             18:プラスチック製品製造業(別掲を除く) 19:ゴム製品製造業 20:なめし革・同製品・毛皮製造業 21:窯業・土石製品製造業 22:鉄鋼業 23:非鉄金属製造業 24:金属製品製造業 25:はん用機械器具製造業 26:生産用機械器具製造業
#             27:業務用機械器具製造業 28:電子部品・デバイス・電子回路製造業 29:電気機械器具製造業 30:情報通信機械器具製造業 31:輸送用機械器具製造業 32:その他の製造業
# F:電気・ガス・熱供給・水道業 => 33:電気業 34:ガス業 35:熱供給業 36:水道業
# G:情報通信業 => 37:通信業 38:放送業 39:情報サービス業 40:インターネット附随サービス業 41:映像・音声・文字情報制作業
# H:運輸業，郵便業 => 42:鉄道業 43:道路旅客運送業 44:道路貨物運送業 45:水運業 46:航空運輸業 47:倉庫業 48:運輸に附帯するサービス業 49:郵便業（信書便事業を含む）
# I:卸売業・小売業 => 50:各種商品卸売業 51:繊維・衣服等卸売業 52:飲食料品卸売業 53:建築材料，鉱物・金属材料等卸売業 54:機械器具卸売業 55:その他の卸売業 56:各種商品小売業 57:織物・衣服・身の回り品小売業 58:飲食料品小売業
#                     59:機械器具小売業 60:その他の小売業 61:無店舗小売業
# J:金融業・保険業 => 62:銀行業 63:協同組織金融業 64:貸金業，クレジットカード業等非預金信用機関 65:金融商品取引業，商品先物取引業 66:補助的金融業等 67:保険業(保険媒介代理業，保険サービス業を含む)
# K:不動産業，物品賃貸業 => 68:不動産取引業 69:不動産賃貸業・管理業 70:物品賃貸業
# L:学術研究，専門・技術サービス業 => 71:学術・開発研究機関 72:専門サービス業(他に分類されないもの) 73:広告業 74:技術サービス業(他に分類されないもの)
# M:宿泊業，飲食サービス業 => 75:宿泊業 76:飲食店 77:持ち帰り・配達飲食サービス業
# N:生活関連サービス業，娯楽業 => 78:洗濯・理容・美容・浴場業 79:その他の生活関連サービス業 80:娯楽業
# O:教育，学習支援業 => 81:学校教育 82:その他の教育，学習支援業
# P:医療，福祉 => 83:医療業 84:保健衛生 85:社会保険・社会福祉・介護事業
# Q:複合サービス事業 => 86:郵便局 87:協同組合(他に分類されないもの)
# R:サービス業（他に分類されないも => 88:廃棄物処理業 89:自動車整備業 90:機械等修理業(別掲を除く) 91:職業紹介・労働者派遣業 92:その他の事業サービス業 93:政治・経済・文化団体 94:宗教 95:その他のサービス業 96:外国公務
# S:公務（他に分類されるものを除く => 97:国家公務 98:地方公務
# T:分類不能の産業 => 99:分類不能の産業
  kiboSangyoDetail: 

# 希望する休日
  kyujitsu: 

# 週休二日
# 年間休日数
# 週所定労働日数
# 時間外
# 希望する就業時間
# 転勤
# 免許・資格
# 学歴
# 経験
# 事業所名

#今日はここまで